# This workflow pulls new gas data

on:
  schedule:
    - cron: '5 23 * * 1'

  workflow_dispatch:

name: pull EIA gas data

env:
  EIA_KEY: ${{ secrets.EIA_KEY }}

jobs:
  render:
    name: Gather latest gas data
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Set up pandoc for Rmd docs
        uses: r-lib/actions/setup-pandoc@v2
      - name: Install dependencies and packages
        run: Rscript -e 'install.packages(c("tidyverse","eia", "janitor", "lubridate","stringr","formattable","data.table","sf","zoo","readxl","jsonlite"))'
      - name: pull data, export files
        run: Rscript scripts/eia_gas_data.R
      - name: Commit results
        run: |
          git add -A
          git commit -m 'New gas data' || echo "No changes"
          git push origin || echo "No changes to commit"
          
